CREATE TABLE IF NOT EXISTS skin_jobs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workshop_url VARCHAR(2048) NOT NULL,
    image_url VARCHAR(2048) NOT NULL,
    status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
