import json

fr_mapping = {
  "evPenalty": "Pénalité",
  "evSkip": "Passer",
  "evSkipAll": "Tout passer",
  "evReverse": "Inverser",
  "evStack": "Empiler",
  "evSwap": "Échanger",
  "evShuffle": "Mélanger",
  "evRotate": "Tourner",
  "evDiscardAll": "Tout défausser",
  "evReshuffle": "Remélanger",
  "evCalled": "Appelé",
  "evForgot": "Oublié",
  "evCaught": "Attrapé",
  "evFalseCall": "Faux appel",
  "evFalseCatch": "Fausse capture",
  "evChallengeWon": "Défi gagné",
  "evChallengeLost": "Défi perdu",
  "evWin": "Victoire",
  "ruleStacking": "Empilement",
  "ruleJumpIn": "Sauter",
  "ruleSevenZero": "Sept Zéro",
  "ruleDrawToMatch": "Piocher pour correspondre",
  "ruleForcePlay": "Jeu forcé",
  "ruleChallenge": "Défi",
  "ruleCallWindow": "Fenêtre d'appel",
  "ruleSeconds": "Secondes",
  "oneCard": "Une carte",
  "cards": "Cartes",
  "catchTitle": "Attraper",
  "catchThem": "Attrapez-les",
  "drawCard": "Piocher une carte",
  "deckLeft": "Cartes restantes",
  "drawStack": "Pioche",
  "waiting": "En attente",
  "challenge": "Défi",
  "challengeHint": "Indice de défi",
  "passTurn": "Passer le tour",
  "mustAnswer": "Doit répondre",
  "callNow": "Appeler maintenant",
  "callOuno": "Appeler Ouno",
  "ounoCalled": "Ouno appelé",
  "chooseColor": "Choisir une couleur",
  "swapWith": "Échanger avec",
  "someoneWon": "Quelqu'un a gagné",
  "ruleCardsUnit": "Unité de cartes",
  "optionalCards": "Cartes optionnelles",
  "houseRules": "Règles maison",
  "presetChaos": "Préréglage Chaos",
  "presetBrutal": "Préréglage Brutal",
  "ruleStartingCards": "Cartes de départ",
  "ruleCallWindowD": "Fenêtre d'appel",
  "ruleForgotPenalty": "Pénalité d'oubli",
  "ruleFalseCall": "Faux appel",
  "ruleFalseCatch": "Fausse capture",
  "ruleAutoPenalty": "Pénalité automatique",
  "ruleAutoPenaltyD": "Pénalité automatique",
  "home.liveCard.competitive": "Compétitif",
  "home.liveCard.ranked": "Classé",
  "home.liveCard.online": "En ligne",
  "profile.clips.error": "Erreur",
  "profile.connections.saved": "Enregistré",
  "profile.connections.saveError": "Erreur d'enregistrement",
  "profile.connections.networkError": "Erreur réseau",
  "profile.connections.hint": "Indice",
  "profile.connections.saving": "Enregistrement",
  "profile.connections.saveButton": "Enregistrer",
  "profile.faceit.error": "Erreur",
  "profile.faceit.unlinked": "Non lié",
  "profile.faceit.recentResults": "Résultats récents",
  "profile.faceit.winShort": "V",
  "profile.faceit.lossShort": "D",
  "profile.faceit.noStats": "Aucune statistique",
  "profile.faceit.kd": "K/D",
  "profile.faceit.adr": "ADR",
  "profile.faceit.matchesCount": "Nombre de matchs",
  "profile.faceit.kr": "K/R",
  "profile.faceit.bestStreak": "Meilleure série",
  "profile.faceit.openingsClutches": "Ouvertures & Clutches",
  "profile.faceit.1v1Won": "1v1 Gagnés",
  "profile.faceit.1v2Won": "1v2 Gagnés",
  "profile.faceit.disclaimer": "Avertissement",
  "profile.featuredClip.loading": "Chargement",
  "profile.featuredClip.empty": "Vide",
  "profile.featuredClip.emptyHint": "Aucun clip mis en avant",
  "profile.featuredClip.source": "Source",
  "profile.featuredClip.playAria": "Lire",
  "profile.stats.ariaLabel": "Statistiques",
  "profile.stats.meters.roundWin": "Victoire de manche",
  "profile.stats.meters.kast": "KAST",
  "profile.stats.meters.headshots": "Tirs à la tête",
  "profile.stats.meters.adr": "ADR",
  "profile.stats.form.lastRounds": "Dernières manches",
  "profile.stats.form.sideT": "Côté T",
  "profile.stats.form.sideCt": "Côté CT",
  "profile.stats.table.rating": "Évaluation",
  "profile.stats.table.kd": "K/D",
  "profile.stats.table.adr": "ADR",
  "profile.stats.table.winPct": "Victoires %",
  "profile.stats.sessions.rds": "Mchs",
  "profile.stats.empty": "Vide",
  "profile.stats.table.map": "Carte",
  "profile.stats.table.rounds": "Manches",
  "profile.stats.table.kast": "KAST",
  "profile.stats.sessions.hs": "HS %",
  "profile.stats.sessions.clutches": "Clutches",
  "profile.stats.sessions.deaths": "Morts",
  "profile.stats.sessions.utilPerRound": "Util par manche",
  "profile.stats.details.openingKills": "Kills d'ouverture",
  "profile.stats.details.openingDeaths": "Morts d'ouverture",
  "profile.stats.details.utilDmg": "Dégâts util",
  "profile.stats.details.plants": "Amorçages",
  "profile.stats.details.ofRounds": "Des manches",
  "social.friends.requestSent": "Demande envoyée",
  "social.friends.error": "Erreur",
  "social.friends.notInLobby": "Pas dans le salon",
  "social.friends.inviteSent": "Invitation envoyée",
  "social.friends.toggleBtn": "Basculer",
  "social.friends.header": "Amis",
  "social.friends.tabFriends": "Amis",
  "social.friends.tabRequests": "Demandes",
  "social.friends.tabAdd": "Ajouter un ami",
  "social.friends.noFriends": "Aucun ami",
  "social.friends.inviteBtn": "Inviter",
  "social.friends.noPending": "Aucune demande en attente",
  "social.friends.steamIdPlaceholder": "ID Steam",
  "social.friends.sendRequest": "Envoyer la demande",
  "social.notifications.accept": "Accepter",
  "social.notifications.dismiss": "Rejeter",
  "stats.charts.splitHint": "Indice de division",
  "stats.charts.rounds": "Manches",
  "stats.howRatingWorks.expected.kills": "Kills attendus",
  "stats.howRatingWorks.expected.killsNote": "Note sur les kills attendus",
  "stats.howRatingWorks.expected.damage": "Dégâts attendus",
  "stats.howRatingWorks.expected.damageNote": "Note sur les dégâts attendus",
  "stats.howRatingWorks.expected.survival": "Survie attendue",
  "stats.howRatingWorks.expected.survivalNote": "Note sur la survie attendue",
  "stats.howRatingWorks.expected.kast": "KAST attendu",
  "stats.howRatingWorks.expected.kastNote": "Note sur le KAST attendu",
  "stats.howRatingWorks.expected.impact": "Impact attendu",
  "stats.howRatingWorks.expected.impactNote": "Note sur l'impact attendu",
  "stats.howRatingWorks.impact.openingKill": "Kill d'ouverture",
  "stats.howRatingWorks.impact.openingDeath": "Mort d'ouverture",
  "stats.howRatingWorks.impact.multikill": "Multikill",
  "stats.howRatingWorks.impact.clutchWon": "Clutch gagné",
  "stats.howRatingWorks.impact.clutchWonValue": "Valeur du clutch gagné",
  "stats.howRatingWorks.impact.tradeKill": "Kill d'échange",
  "stats.howRatingWorks.impact.tradeKillValue": "Valeur du kill d'échange",
  "stats.howRatingWorks.impact.flashAssist": "Assistance flash",
  "stats.howRatingWorks.impact.flashAssistValue": "Valeur de l'assistance flash",
  "stats.howRatingWorks.impact.utilityDamage": "Dégâts utilitaires",
  "stats.howRatingWorks.impact.utilityDamageValue": "Valeur des dégâts utilitaires",
  "stats.howRatingWorks.impact.teamKillLive": "Kill d'équipe (En direct)",
  "stats.howRatingWorks.impact.teamKillDecided": "Kill d'équipe (Décidé)",
  "stats.howRatingWorks.impact.bombPlantDefuse": "Bombe amorcée/désamorcée",
  "stats.howRatingWorks.impact.bombPlantDefuseValue": "Valeur d'amorçage/désamorçage",
  "stats.howRatingWorks.title": "Comment fonctionne l'évaluation",
  "stats.howRatingWorks.subtitle": "Sous-titre",
  "stats.howRatingWorks.ratingHeading": "Évaluation",
  "stats.howRatingWorks.ratingDesc1": "Description de l'évaluation 1",
  "stats.howRatingWorks.ratingDesc2": "Description de l'évaluation 2",
  "stats.howRatingWorks.ratingDesc3": "Description de l'évaluation 3",
  "stats.howRatingWorks.ratingSum1": "Résumé de l'évaluation 1",
  "stats.howRatingWorks.ratingSum2": "Résumé de l'évaluation 2",
  "stats.howRatingWorks.ratingSum3": "Résumé de l'évaluation 3",
  "stats.howRatingWorks.ratingSum4": "Résumé de l'évaluation 4",
  "stats.howRatingWorks.averageHeading": "Moyenne",
  "stats.howRatingWorks.averageDesc": "Description de la moyenne",
  "stats.howRatingWorks.impactHeading": "Impact",
  "stats.howRatingWorks.impactDesc": "Description de l'impact",
  "stats.howRatingWorks.plantingHeading": "Amorçage",
  "stats.howRatingWorks.plantingDesc1": "Description de l'amorçage 1",
  "stats.howRatingWorks.alreadyPlanted": "Déjà amorcé",
  "stats.howRatingWorks.plantingDesc2": "Description de l'amorçage 2",
  "stats.howRatingWorks.tkHeading": "Kills d'équipe",
  "stats.howRatingWorks.tkDesc": "Description des kills d'équipe",
  "stats.howRatingWorks.csRatingHeading": "Évaluation CS",
  "stats.howRatingWorks.csRatingDesc": "Description de l'évaluation CS",
  "stats.howRatingWorks.eloDesc1": "Description Elo 1",
  "stats.howRatingWorks.eloDesc2": "Description Elo 2",
  "stats.howRatingWorks.eloBounds1": "Limites Elo 1",
  "stats.howRatingWorks.eloBounds2": "Limites Elo 2",
  "stats.howRatingWorks.eloBounds3": "Limites Elo 3",
  "stats.howRatingWorks.seasonHeading": "Saison",
  "stats.howRatingWorks.seasonDesc": "Description de la saison",
  "stats.leaderboardTabs.ariaLabel": "Onglets du classement",
  "stats.leaderboardTabs.player": "Joueur",
  "stats.leaderboardTabs.noData": "Aucune donnée",
  "feed.backToFeed": "Retour au fil",
  "feed.noProfileTooltip": "Aucun profil",
  "puzzleNo": "Puzzle n°",
  "tagline": "Slogan",
  "modeDaily": "Quotidien",
  "modeEndless": "Sans fin",
  "modeDailyD": "Mode Quotidien",
  "modeEndlessD": "Mode Sans fin",
  "modeRace": "Course",
  "playWithFriends": "Jouer avec des amis",
  "streak": "Série",
  "bestStreak": "Meilleure série",
  "played": "Joué",
  "avgGuesses": "Tentatives moyennes",
  "loadFailed": "Échec du chargement",
  "retry": "Réessayer",
  "loading": "Chargement",
  "searchPlaceholder": "Rechercher...",
  "noMatches": "Aucun résultat",
  "oneGuess": "1 Tentative",
  "guessCount": "Tentatives",
  "giveUp": "Abandonner",
  "newPro": "Nouveau Pro",
  "colPlayer": "Joueur",
  "dataFrom": "Données de",
  "solved": "Résolu",
  "theAnswerWas": "La réponse était",
  "colMajors": "Majeurs",
  "solvedIn": "Résolu en",
  "copied": "Copié",
  "share": "Partager",
  "playEndless": "Jouer sans fin",
  "patchLabel": "Patch",
  "newChampion": "Nouveau champion",
  "colChampion": "Champion",
  "stats.compare.rating": "Évaluation",
  "stats.compare.kd": "K/D",
  "stats.compare.adr": "ADR",
  "stats.compare.kast": "KAST",
  "stats.compare.hs": "HS %",
  "stats.compare.winPct": "Victoires %",
  "stats.compare.kpr": "KPR",
  "stats.compare.assists": "Assistances",
  "stats.compare.openingKills": "Kills d'ouverture",
  "stats.compare.openingDeaths": "Morts d'ouverture",
  "stats.compare.clutches": "Clutches",
  "stats.compare.multiKills": "Multi Kills",
  "stats.compare.tradeKills": "Kills d'échange",
  "stats.compare.enemiesFlashed": "Ennemis flashés",
  "stats.compare.plants": "Amorçages",
  "stats.compare.defuses": "Désamorçages",
  "stats.compare.utilPerRound": "Util par manche",
  "stats.compare.roundsPlayed": "Manches jouées",
  "stats.compare.noSeason": "Aucune saison",
  "stats.maps.globalStats": "Statistiques globales",
  "stats.maps.noSeason": "Aucune saison",
  "stats.maps.globalStatsSeason": "Saison de statistiques globales",
  "stats.maps.overview": "Aperçu",
  "stats.maps.mapHeatmaps": "Cartes thermiques",
  "stats.maps.heatmapTitle": "Carte thermique",
  "stats.maps.heatmapDesc": "Description de la carte thermique",
  "stats.maps.map": "Carte",
  "stats.maps.serverAvg": "Moyenne du serveur",
  "stats.maps.roundsOnMap": "Manches sur la carte",
  "seasons.history": "Historique",
  "seasons.everySeason": "Chaque saison",
  "seasons.description": "Description",
  "seasons.title": "Saisons",
  "seasons.recorded": "Enregistré",
  "seasons.ongoing": "En cours",
  "seasons.days": "Jours",
  "seasons.players": "Joueurs",
  "seasons.rankedRounds": "Manches classées",
  "seasons.avgElo": "Elo moyen",
  "seasons.avgAdr": "ADR moyen",
  "seasons.avgKd": "K/D moyen",
  "seasons.champion": "Champion",
  "seasons.peakElo": "Elo max",
  "legendTitle": "Légende",
  "legendHit": "Touché",
  "legendNear": "Proche",
  "legendMiss": "Raté",
  "legendArrow": "Flèche",
  "correctUnit": "Correct",
  "targetScoreD": "Score cible",
  "targetScore": "Score cible",
  "roundTimer": "Chrono de manche",
  "revealAfter": "Révéler après",
  "revealAfterD": "Révéler après",
  "raceYou": "Vous",
  "raceTitle": "Course",
  "raceScore": "Score de la course",
  "raceRevealIn": "Révélation dans",
  "raceRivals": "Rivaux",
  "raceWon": "Course gagnée",
  "raceLost": "Course perdue",
  "raceStandings": "Classement",
  "raceRun": "Essai",
  "raceGuessing": "Supposition...",
  "evStart": "Démarrer",
  "evSolved": "Résolu",
  "evRevealed": "Révélé",
  "evTimeout": "Temps écoulé",
  "question": "Question",
  "difficulty": "Difficulté",
  "resultPerfect": "Parfait",
  "resultGreat": "Super",
  "resultOk": "OK",
  "resultPoor": "Faible",
  "modePractice": "Pratique",
  "modePracticeD": "Mode Pratique",
  "bestScore": "Meilleur score",
  "accuracy": "Précision",
  "alreadyPlayed": "Déjà joué",
  "yourResult": "Votre résultat",
  "harder": "Plus difficile",
  "inputPlaceholder": "Entrez du texte...",
  "correct": "Correct",
  "wrong": "Faux",
  "finish": "Terminer",
  "next": "Suivant",
  "resultTitle": "Résultat",
  "playAgain": "Rejouer",
  "waitingOthers": "En attente des autres..."
}

with open('missing2_part2.json', 'r') as f:
    keys = json.load(f)

fr_dict = {}
for key in keys:
    if key in fr_mapping:
        fr_dict[key] = fr_mapping[key]
    else:
        # should only happen if I missed something above
        print("MISSING IN FR:", key)
        fr_dict[key] = key

with open('fr_guessed_2.json', 'w') as f:
    json.dump(fr_dict, f, indent=2)

print("Generated fr template")
