import json

with open('en_guessed_1.json', 'r') as f:
    en_dict = json.load(f)

# Hardcoded precise translations
translations = {
    "Discord": "Discord",
    "Linked": "Associé",
    "Unlinked": "Non associé",
    "Busy": "Occupé",
    "Unlink": "Dissocier",
    "Link Title": "Associer",
    "Connect": "Connecter",
    "Sign In": "Se connecter",
    "Google": "Google",
    "Failed Prefix": "Échec",
    "Failed Message": "Message d'échec",
    "Job": "Tâche",
    "None": "Aucun",
    "Status": "Statut",
    "Done Prefix": "Terminé",
    "Done Message": "Message de fin",
    "Pipeline Failed Prefix": "Échec du pipeline",
    "Pipeline Failed Message": "Message d'échec du pipeline",
    "Unread Count": "Nombre non lu",
    "Eyebrow": "Sur-titre",
    "Title Prefix": "Préfixe du titre",
    "Title Suffix": "Suffixe du titre",
    "Description Prefix": "Préfixe de la description",
    "During": "Pendant",
    "Description Suffix": "Suffixe de la description",
    "Ladder": "Classement",
    "Player": "Joueur",
    "Wins": "Victoires",
    "Losses": "Défaites",
    "Winrate": "Taux de victoire",
    "Challenges Won": "Défis remportés",
    "No Duels": "Aucun duel",
    "Recent Duels": "Duels récents",
    "When Utc": "Quand UTC",
    "Winner": "Gagnant",
    "Loser": "Perdant",
    "Arena": "Arène",
    "Map": "Carte",
    "Type": "Type",
    "Challenge": "Défi",
    "Rotation": "Rotation",
    "Title": "Titre",
    "Sign In Prompt": "Invite de connexion",
    "Ranked Only Note": "Note classée uniquement",
    "All Rounds Note": "Note toutes les manches",
    "Ranked Only": "Classé uniquement",
    "Steam Id Prefix": "Préfixe ID Steam",
    "Edit Profile": "Modifier le profil",
    "Description": "Description",
    "Overview": "Vue d'ensemble",
    "Being Rebuilt": "En cours de reconstruction",
    "Map Heatmaps": "Cartes de chaleur",
    "Seasons History": "Historique des saisons",
    "Compare Players": "Comparer les joueurs",
    "Error Loading": "Erreur de chargement",
    "Error Server": "Erreur serveur",
    "Loading": "Chargement",
    "Demos Waiting": "Démos en attente",
    "Demos Waiting Hint": "Astuce démos en attente",
    "Clip Marks": "Marques de clip",
    "Clip Marks Hint": "Astuce marques de clip",
    "Unnamed Clips": "Clips sans nom",
    "Unnamed Clips Hint": "Astuce clips sans nom",
    "Active Bans": "Bannissements actifs",
    "Active Bans Hint": "Astuce bannissements actifs",
    "Players Known": "Joueurs connus",
    "Players Known Hint": "Astuce joueurs connus",
    "Clips Posted": "Clips publiés",
    "Clips Posted Hint": "Astuce clips publiés",
    "Lineups Saved": "Alignements sauvegardés",
    "Lineups Saved Hint": "Astuce alignements sauvegardés",
    "Admin Actions": "Actions d'administration",
    "Admin Actions Hint": "Astuce actions d'administration",
    "Poll Open": "Sondage ouvert",
    "Poll Closed": "Sondage fermé",
    "Poll None": "Aucun sondage",
    "Season": "Saison",
    "Season Info": "Infos saison",
    "Season Id": "ID de la saison",
    "Season None": "Aucune saison",
    "Season Vote": "Vote de la saison",
    "Error Load Config": "Erreur de chargement",
    "Error Network": "Erreur réseau",
    "Error Save Failed": "Échec de la sauvegarde",
    "Saved": "Sauvegardé",
    "Error Network Write": "Erreur d'écriture réseau",
    "Config File": "Fichier de configuration",
    "Unavailable": "Indisponible",
    "Reading Config": "Lecture de la configuration",
    "Live Config Note": "Note de configuration en direct",
    "Read Only": "Lecture seule",
    "Read Only Note": "Note de lecture seule",
    "Failed": "Échec",
    "Saved Changes": "Changements sauvegardés",
    "Config Sections": "Sections de configuration",
    "Unsaved Changes": "Changements non sauvegardés",
    "Apply Changes": "Appliquer les changements",
    "Apply Warning": "Avertissement d'application",
    "Title": "Titre",
    "Desc1": "Desc 1",
    "Desc2": "Desc 2",
    "Empty Section": "Section vide",
    "Changed": "Modifié",
    "On": "Actif",
    "Off": "Inactif",
    "You Label": "Vous",
    "Phase Submit": "Phase de soumission",
    "Phase Judge": "Phase de jugement",
    "Phase Reveal": "Phase de révélation",
    "Round": "Manche",
    "Leave Game": "Quitter la partie",
    "Pick Text": "Choisir texte",
    "You Are Czar": "Vous êtes le Tsar",
    "Waiting Count": "Compte en attente",
    "Submitted Wait": "Attente de soumission",
    "Custom Card": "Carte personnalisée",
    "Back To Hand": "Retour en main",
    "Submit Custom": "Soumettre personnalisé",
    "Custom Hint": "Astuce personnalisée",
    "Submit": "Soumettre",
    "Write Custom": "Écrire personnalisé",
    "Tap To Pick": "Appuyez pour choisir",
    "Czar Picks": "Choix du Tsar",
    "Round Winner": "Gagnant de la manche",
    "Next Round": "Manche suivante",
    "Next In": "Suivant dans",
    "Game Over": "Fin de partie",
    "Points": "Points",
    "Recap": "Récapitulatif",
    "Return Lobby": "Retour au salon",
    "Rounds": "Manches",
    "Infinite": "Infini",
    "Seconds": "Secondes",
    "Allow Custom": "Autoriser personnalisé",
    "Options Title": "Options",
    "Timer": "Minuteur",
    "Allow Custom D": "Autoriser personnalisé D",
    "Red": "Rouge",
    "Blue": "Bleu",
    "Kind Red": "Type rouge",
    "Kind Blue": "Type bleu",
    "Kind Neutral": "Type neutre",
    "Kind Assassin": "Type assassin",
    "Kind Double": "Type double",
    "Your Turn Clue": "Votre tour indice",
    "Your Turn Guess": "Votre tour devinette",
    "Spectating": "Spectateur",
    "Waiting Clue": "Attente d'indice",
    "Waiting Guess": "Attente de devinette",
    "Brand": "Marque",
    "Phase Clue": "Phase d'indice",
    "Phase Guess": "Phase de devinette",
    "Red Team": "Équipe rouge",
    "Clue Is": "L'indice est",
    "Unlimited": "Illimité",
    "Unlimited Guesses": "Devinettes illimitées",
    "One Guess Left": "Une devinette restante",
    "Guesses Left": "Devinettes restantes",
    "Clue Placeholder": "Espace réservé indice",
    "Clue Count": "Nombre d'indices",
    "Give Clue": "Donner un indice",
    "Must Guess Once": "Doit deviner une fois",
    "End Guessing": "Terminer les devinettes",
    "Spymaster Hold": "Pause maître-espion",
    "Key Card": "Carte clé",
    "Clue Rejected": "Indice rejeté",
    "Blue Team": "Équipe bleue",
    "Wins Assassin": "Victoires assassin",
    "Wins Forfeit": "Victoires forfait",
    "Wins Agents": "Victoires agents",
    "You Won": "Vous avez gagné",
    "You Lost": "Vous avez perdu",
    "Agents Left": "Agents restants",
    "Log Start": "Début du journal",
    "Log Clue": "Journal d'indice",
    "Log Pick": "Journal de choix",
    "Log Double": "Journal de double",
    "Log Clue Timeout": "Expiration journal indice",
    "Log New Spymaster": "Nouveau maître-espion",
    "Log Win": "Journal victoire",
    "No Timer": "Pas de minuteur",
    "Board Size": "Taille du plateau",
    "Presets Title": "Préréglages",
    "Preset Classic": "Préréglage classique",
    "Preset Blitz": "Préréglage blitz",
    "Preset Deadly": "Préréglage mortel",
    "First Team": "Première équipe",
    "First Random": "Premier aléatoire",
    "Assassins": "Assassins",
    "Assassins D": "Assassins D",
    "Packs": "Packs",
    "Packs Hint": "Astuce de packs",
    "Clue Timer": "Minuteur d'indice",
    "Turn Timer": "Minuteur de tour",
    "Rounds Unit": "Unité de manches",
    "Words From": "Mots de",
    "Lang French": "Français",
    "Lang English": "Anglais",
    "Rounds Hint": "Astuce manches",
    "Phase Gif": "Phase Gif",
    "Phase Caption": "Phase de légende",
    "Phase Vote": "Phase de vote",
    "Phase Results": "Résultats de la phase",
    "Pick Gif": "Choisir Gif",
    "Search Gif": "Chercher Gif",
    "Paste Gif Url": "Coller URL Gif",
    "Caption Slot": "Emplacement légende",
    "Write Caption": "Écrire légende",
    "Submitted": "Soumis",
    "Voted": "Voté",
    "Tap To Vote": "Appuyer pour voter",
    "Yours": "Le vôtre",
    "One Vote": "Un vote",
    "Votes": "Votes",
    "Mode Gif": "Mode Gif",
    "Mode Caption": "Mode Légende",
    "Custom Count": "Compte personnalisé",
    "Invalid Url": "URL invalide",
    "Answer Mode": "Mode de réponse",
    "Mode Caption D": "Mode Légende D",
    "Mode Gif D": "Mode Gif D",
    "Caption Time": "Temps de légende",
    "Vote Time": "Temps de vote",
    "Template Packs": "Packs de modèles",
    "Custom Memes": "Mèmes personnalisés",
    "Add Meme": "Ajouter un mème",
    "Remove": "Supprimer",
    "You": "Vous",
    "Bot": "Bot",
    "Doubles": "Doubles",
    "Your Turn": "Votre tour",
    "Turn Of": "Tour de",
    "Properties": "Propriétés",
    "In Jail": "En prison",
    "Bankrupt": "En faillite",
    "Rolled": "Lancé",
    "Log": "Journal",
    "Rolling": "En cours de lancement",
    "Roll Dice": "Lancer les dés",
    "Buy": "Acheter",
    "Skip": "Passer",
    "End Turn": "Fin de tour",
    "Pay Jail": "Payer prison",
    "Use Card": "Utiliser carte",
    "Chance Deck": "Paquet chance",
    "Chest Deck": "Paquet caisse commune",
    "Base Rent": "Loyer de base",
    "With Set": "Avec ensemble",
    "With Houses": "Avec maisons",
    "With Hotel": "Avec hôtel",
    "Rail Rent": "Loyer de gare",
    "Util Rent": "Loyer d'utilitaire",
    "Price": "Prix",
    "Per House": "Par maison",
    "Owned By": "Appartenant à",
    "Unowned": "Non possédé",
    "Mortgaged": "Hypothéqué",
    "Build Hotel": "Construire hôtel",
    "Build House": "Construire maison",
    "Sell House": "Vendre maison",
    "Mortgage": "Hypothéquer",
    "Unmortgage": "Dés-hypothéquer",
    "Mode 2v2": "Mode 2v2",
    "Mode Ffa": "Mode FFA",
    "Board": "Plateau",
    "Board Hint": "Astuce plateau",
    "Tiles": "Tuiles",
    "Custom": "Personnalisé",
    "Edit Boards": "Modifier plateaux",
    "Test Buildings": "Tester bâtiments",
    "Mode": "Mode",
    "Mode Ffa D": "Mode FFA D",
    "Mode 2v2 D": "Mode 2v2 D",
    "You Are Drawing": "Vous dessinez",
    "Is Drawing": "Dessine",
    "Is Choosing": "Choisit",
    "Choose Word": "Choisir mot",
    "Auto Pick": "Choix auto",
    "The Word Was": "Le mot était",
    "Next Turn": "Prochain tour",
    "Eraser": "Gomme",
    "Undo": "Annuler",
    "Clear": "Effacer",
    "You Guessed": "Vous avez deviné",
    "Guessed It": "Deviné",
    "Close Guess": "Presque deviné",
    "Guess Placeholder": "Espace réservé devinette",
    "Guessed": "Deviné",
    "Waiting To Start": "En attente de démarrage",
    "Ev Draw": "Ev Dessin",
    "Reload": "Recharger",
    "No Changes": "Aucun changement",
    "Review Changes": "Examiner les changements",
    "Cancel": "Annuler",
    "Save Only": "Sauvegarder uniquement",
    "Save Apply Now": "Sauvegarder et appliquer maintenant",
    "Saving": "Sauvegarde en cours",
    "Save Apply": "Sauvegarder et appliquer",
    "Joueurs minimum": "Joueurs minimum",
    "Morts": "Morts",
    "Victoires %": "Victoires %"
}

fr_dict = {}

# Some exact mapping needs from prompt:
hardcoded_fr_override = {
    "admin.pluginConfig.on": "Actif",
    "admin.pluginConfig.off": "Inactif",
    "Ranked.MinPlayers": "Joueurs minimum",
    "profile.stats.sessions.deaths": "Morts",
    "profile.stats.table.winPct": "Victoires %",
    "profile.signInButton": "Se connecter",
    "settings.signInButton": "Se connecter",
}

for k, v in en_dict.items():
    if k in hardcoded_fr_override:
        fr_dict[k] = hardcoded_fr_override[k]
    else:
        fr_dict[k] = translations.get(v, v)

with open('fr_guessed_1.json', 'w') as f:
    json.dump(fr_dict, f, indent=2)

