import { decodeMapMesh } from "@/lib/utility3d";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

/**
 * The converter and the viewer have to agree, so this drives the real
 * converter and decodes its real output. Building its own fixture rather than
 * expecting one to be lying around: a test that passes only because of a file
 * somebody left behind is a test that fails on a fresh clone.
 */

let fails = 0;
const check = (n: string, c: boolean, extra = "") => {
  console.log((c ? "ok   " : "FAIL ") + n + (c ? "" : "  " + extra));
  if (!c) fails++;
};

const ROOT = path.resolve(import.meta.dirname, "..", "..");
const MAP = "de_converterselftest";
const meshPath = path.join(ROOT, "public", "maps3d", `${MAP}.mesh`);
const objPath = path.join(os.tmpdir(), `${MAP}.obj`);

// A box with quad faces and shared corners — what an exporter actually emits.
fs.writeFileSync(
  objPath,
  [
    "# generated by roundtrip.test.mts",
    "v 0 0 0", "v 4000 0 0", "v 4000 4000 0", "v 0 4000 0",
    "v 0 0 500", "v 4000 0 500", "v 4000 4000 500", "v 0 4000 500",
    "f 1 2 3 4", "f 5 6 7 8", "f 1 2 6 5",
    "f 3 4 8 7", "f 1 4 8 5", "f 2 3 7 6",
  ].join("\n"),
);

try {
  const run = spawnSync(
    process.execPath,
    [path.join(ROOT, "tools", "convert-map-mesh.mjs"), MAP, objPath],
    { encoding: "utf8" },
  );
  check("the converter runs", run.status === 0, run.stderr);
  check("  and welds 8 corners out of 6 quads", /8 vertices in, 8 after welding/.test(run.stdout), run.stdout);
  check("  reporting 12 triangles", /12 triangles/.test(run.stdout), run.stdout);
  check("  and the map's real span", /4000 × 4000 × 500 units/.test(run.stdout), run.stdout);

  const bytes = fs.readFileSync(meshPath);
  const mesh = decodeMapMesh(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength));

  check("the viewer decodes what the converter wrote", mesh.triangles === 12, String(mesh.triangles));
  check("vertices welded to the box's 8 corners", mesh.positions.length === 24, String(mesh.positions.length / 3));
  check("bounds survive the round trip",
    mesh.bounds.min.join() === "0,0,0" && mesh.bounds.max.join() === "4000,4000,500",
    JSON.stringify(mesh.bounds));
  check("every index is in range", mesh.indices.every((i) => i < mesh.positions.length / 3));
  check("no degenerate triangles survived", (() => {
    for (let i = 0; i < mesh.indices.length; i += 3) {
      const [a, b, c] = [mesh.indices[i], mesh.indices[i + 1], mesh.indices[i + 2]];
      if (a === b || b === c || a === c) return false;
    }
    return true;
  })());

  // A prop-sized export should be called out rather than silently accepted.
  const small = path.join(os.tmpdir(), "de_smallselftest.obj");
  fs.writeFileSync(small, ["v 0 0 0", "v 10 0 0", "v 10 10 0", "f 1 2 3"].join("\n"));
  const warned = spawnSync(
    process.execPath,
    [path.join(ROOT, "tools", "convert-map-mesh.mjs"), "de_smallselftest", small],
    { encoding: "utf8" },
  );
  check("a prop-sized export is flagged", /small for a map/.test(warned.stdout + warned.stderr));
  fs.rmSync(small, { force: true });
  fs.rmSync(path.join(ROOT, "public", "maps3d", "de_smallselftest.mesh"), { force: true });
} finally {
  fs.rmSync(objPath, { force: true });
  fs.rmSync(meshPath, { force: true });
}

console.log(fails ? `\n${fails} FAILED` : "\nall passed");
process.exit(fails ? 1 : 0);
