CREATE TABLE IF NOT EXISTS `GardenProfileLinks` (
  `SteamId`   BIGINT NOT NULL,
  `Provider`  VARCHAR(16) NOT NULL,
  `Handle`    VARCHAR(160) NOT NULL DEFAULT '',
  `Public`    TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`SteamId`,`Provider`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
